- index.html
> Made mobile responsive

- index.html
Respected Sir,
I have added a link to the t-shirt so users can easily access the website. Hope it works and thanks for your acceptance. Thank You
> Added Link to T-Shirt

- index.html
This change will help the developers to understand the index.html file more easily.
> Moved all the inline css to internal css

- index.html
modified steps display as list
> steps to be followed portion modified

- README.md
Reverts rakshit234/HacktoberFest2020#20
> Revert "Update image because I also want t shirt thanks bro"

- index.html
Respected Sir,
I have made some changes to "Steps to be followed" the text formating. You may like it. Thank You
> Updated text format

- README.md
Reverts rakshit234/HacktoberFest2020#24
> Revert "Revert "Update image because I also want t shirt thanks bro""

- index.html
- style.css
Added styling to the list containing steps to be followed
> edit steps to be followed

- README.md
Hi,Rakshit!
I have added The event date so that viewer's of this repo will be get aware of this event.
STAY HOME,STAY SAFE
> Event Date!

- README.md
Added some valuable points to the readme
> Added some more valuable points in the readme

- index.html
- style.css
Changed border of image with little radius.
> Changed border of image

- style.css
> btn hover added

- style.css
Add negative sticky margin to be filled the full size of the screen
BEFORE :framed_picture: 
NOW :framed_picture:
> Add negative margin to the sticky to fill 100%

- index.html
- style.css
Changed the site design of tshirt and steps to look side by side
> Changed the design on tshirt and steps to look better

- index.html
- style.css
> Added glow css and implemented to Steps to Follow

- index.html
- style.css
Glow? No. It doesn't look good.
> Updated HTML and CSS

- index.html
- style.css
1. Modified CSS to add transitions for the rules section and t-shirt image upon hover effect.
2. Cleaned code by removing some CSS codes from index.html and adding to styles.css.
3. Modified margin for the logo.
> Changes to UI : Transitions on hover added

- index.html
- style.css
Added alternate sections and changed styling
> add sections and styling

- README.md
> add footer to readme.md file

- index.html
- style.css
I Have Changed The Fonts Of Headings And Changed A Color Scheme to make it more eye catching.
> Changed The UI and Fonts

- index.html
Added more clarity to the steps needed to be taken during hacktoberfest, due to spam PRs, only PRs labelled 'Hacktoberfest' are valid, I have updated the steps to reflect this.
> Updated Index.HTML - Added more description on steps

- index.html
Added a link to Digital Ocean and a link to their Twitter account usi…ng FontAwesome.
> Added a link to Digital Ocean in the footer

- LICENSE
- index.html
Added a open source copyright statement from MIT, and then implemented a link inside of the website that leads to the copyright statement from MIT. The link may be wrong, but it may be able to be formatted differently so it leads straight to the statement.
> Added copyright License and Link

- style.css
Hey Maintainer,
I fixed the issue of text cutting off the screen for paragraph title in the mobile view of the site giving better view and mobile browser compatibility.
Before:
After:
Kindly review my PR. ✌
> Fixed font size issue for better mobile browser compatibility

- index.html
- style.css
Major changes: Added encouragement for planting tree and changed the scroll bar
Minor changes: Changed the font for some text and changed the color of box-shadow
> Pull request for Hacktoberfest 2020

- index.html
- style.css
I added link to updated PR rules
Other changes are code formatting fixes
> Added updated rules link

- index.html
- style.css
I aligned the footer to the bottom giving it color that sticks with the theme. 
Also updated the body styling so that the new sections coming in do not affect the footer.
Hope you like the updates.
Thanks.
> fixed body color, margin, padding and added the content in footer fixing it to the bottom

- index.html
- style.css
I've made social media links into an attractive neon theme
> changes into index

- index.html
- style.css
I have added glowing effect on hovering in Tshirt. I hope u like my modification. For any quires u can comment. I hope u accect my PR
> added glowing hover effect on tshirt

- style.css
in my prev pr the style of countdown was not merged so the style of countdown is added in this
> 1 new commit in the countdown style
